language: php
dist: trusty

sudo: required

addons:
  postgresql: "9.6"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm


matrix:
  include:
    - php: 5.4
      env: DB=mysqli MOODLE_BRANCH=MOODLE_26_STABLE
    - php: 5.6
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_26_STABLE
    - php: 5.4
      env: DB=mysqli MOODLE_BRANCH=MOODLE_27_STABLE
    - php: 5.6
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_27_STABLE
    - php: 5.4
      env: DB=mysqli MOODLE_BRANCH=MOODLE_29_STABLE
    - php: 5.6
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_29_STABLE
    - php: 5.4
      env: DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE
    - php: 7.0
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_31_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE
    - php: 7.1
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_33_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.3
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.3
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=master
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=master
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=master
    - php: 7.3
      env: DB=pgsql  MOODLE_BRANCH=master

before_install:
  - export MOODLE_VERSION=$(echo "$MOODLE_BRANCH" | cut -d'_' -f 2)
  - phpenv config-rm xdebug.ini
  - cd ../..
  - if [ "$MOODLE_VERSION" = 36 ] || [ "$MOODLE_VERSION" -le 34 ]; then NVMVERSION=8.9; else NVMVERSION=14.0.0; fi
  - nvm install $NVMVERSION;
  - nvm use $NVMVERSION;
  - if [ "$MOODLE_VERSION" = "master" ] || [ "$MOODLE_VERSION" -ge 32 ]; then CI=2; else CI=1; fi
  - echo $CI
  - if [ "$CI" = 2 ]; then
      composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2;
    else
      composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^1;
    fi
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install -vvv

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit
  - if [ "$CI" -eq 2 ]; then moodle-plugin-ci phpdoc     ; fi
  - if [ "$CI" -eq 2 ]; then moodle-plugin-ci savepoints ; fi
  - if [ "$CI" -eq 2 ]; then moodle-plugin-ci mustache   ; fi
  - if [ "$CI" -eq 2 ]; then moodle-plugin-ci grunt      ; fi
